### ISSUE TITLE
Latest build fails on startup / after adding any job

### ISSUE THREAD

**Issue by bedge** [rondorn/CiPol#3]
Upgraded to 1.0.3 and it's failing in a couple of different ways.

1) I had to delete my cfg file: ~/Library/Containers/com.rdorn.CiPol/Data/Documents/ci-monitor.json to get the app to start.
With that file in place it terminates on startup.

2) With no cfg file, it starts and I was able to add the server, but as soon as I added a job it died with this error:

```
)
, "lastSuccessfulBuild": {
    "_class" = "org.jenkinsci.plugins.workflow.job.WorkflowRun";
    number = 5214;
    url = "http://rscjenkssndbox.eth.rsshpc1.sc1.science.roche.com:8080/job/NGHC/job/nghc-ami-builder/job/develop/5214/";
}, "firstBuild": {
    "_class" = "org.jenkinsci.plugins.workflow.job.WorkflowRun";
    number = 1;
    url = "http://rscjenkssndbox.eth.rsshpc1.sc1.science.roche.com:8080/job/NGHC/job/nghc-ami-builder/job/develop/1/";
}]
Looking up serverName for
Json Output userName is
Json Output password is REDACTED
Json Output urlString is /job//5214/api/json
https error = 0
returned Json Output json = ["httpStatus": "Recieved http error 0"]
lastRunTime = lastRun /job/NGHC//job/nghc-ami-builder/job/develop = 0.0
lastRunTime = localTime /job/NGHC//job/nghc-ami-builder/job/develop = 1614697704.335081
lastRunTime = timeDiff /job/NGHC//job/nghc-ami-builder/job/develop = 1614697704.335
lastCompletedBuildNumber = 5214 lastBuildNumber = 5214
New Job Testing Status is ["timeDiffDouble": "1614697704.335", "lastPolled": "07:08 AM 03-02 ", "status": "Idle", "lastJobStatus": "Passing", "timeDiffString": "18,689 days", "pollingStatus": "ok"]
New Job Testing Status is true
jenkinsServerData, data equals ["rscjenkssndbox": CiPol.JenkinsServerPrefHandler]
Working on job Name (key: "/job/NGHC//job/nghc-ami-builder/job/develop", value: CiPol.JenkinsJobPrefHandler)
zsh: illegal hardware instruction  /Applications/CiPol.app/Contents/MacOS/CiPol
```

Did I get an M1 version or something?

**Comment by rondorn** [comment]
No, let me investigate and see if I can reproduce.

**Comment by rondorn** [comment]
Ok, I 'think' I might know what going on based on some googling.

https://stackoverflow.com/questions/45774995/swift-illegal-hardware-instruction-in-while-loop

This seems to indicate that there is a VERY large number overflowing a buffer and leading to this error. I 'suspect' this might be due to my date calculations (when the job was last run). If this is the issue, I have converted the variable from a double to an UInt64, and this may very well resolve the issue. I can't be certain though, since I am unable to reproduce. Whatever the issue is, I suspect some aspect of the job you're pointing towards is causing the issue. I doubt that your Jenkins server is accessible to me, so hopefully I am guessing right as to the cause.

Try the following build (this is a link to a digitally signed app outside the App Store for this beta) and let me know if this resolves the issue.

https://www.dropbox.com/s/evpypj0ejcwdh1c/CiPol.zip?dl=1

The output you provided indicates the jenkins job was last tested 18,689 days ago or 51.2 years, so I suspect some bad or unexpected data is getting in there. Curious if you can look at your Jenkins and help me understand why this is happening. If you go to {jenkins ur}/job/{job name}/{job number}/api/json?pretty=1

There is a timestamp line I am looking at and comparing to real time.

See this example on a public apache Jenkins server

https://builds.apache.org/job/ActiveMQ/job/ActiveMQ/job/PR-572/api/json?pretty=1

I'm giving you this sorry detail in the hopes that I can change my code to avoid these issues if they are still happening.

Thanks

**Comment by rondorn** [comment]
Ok, actually I think I reproduced the issue. I have uploaded version 1.0.5(22) to the App Store and once that is approved that 'should' resolve the issues. Please confirm after you are using this version.

Thanks

**Comment by bedge** [comment]
The build you shared does not have the problem.

thanks!

**Comment by rondorn** [comment]
There is a new version on the App Store with the fix
